# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a2ausers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QU', 'Comment on question'), ('AN', 'Comment on answer')], default='AN', max_length=2)),
                ('parent_id', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='a2ausers.A2AUser')),
            ],
        ),
    ]
