# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2ausers', '0003_a2auser_followed_users'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='topic',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followed_topics', to='a2ausers.A2AUser'),
        ),
    ]
