# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='A2AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a2ausers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A2A User',
                'verbose_name_plural': 'A2A Users',
            },
        ),
    ]
