# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2ausers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2auser',
            name='num_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='a2auser',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='a2auser',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='a2auser',
            name='num_unread_notis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='a2auser',
            name='num_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
