# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2ausers', '0002_auto_20160609_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2auser',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='_a2auser_followed_users_+', to='a2ausers.A2AUser'),
        ),
    ]
