# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2ausers', '0003_a2auser_followed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2auser',
            name='avatar',
            field=models.ImageField(default='client/static/img/default.jpg', upload_to='client/static/img/'),
        ),
    ]
