# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 02:25
from __future__ import unicode_literals

import a2ausers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2ausers', '0004_a2auser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2auser',
            name='avatar',
            field=models.ImageField(default='client/static/img/default.jpg', upload_to=a2ausers.models.img_path),
        ),
    ]
