# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('num_answers', models.IntegerField(default=0)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='posts.Post')),
                ('topics', models.ManyToManyField(blank=True, related_name='questions', to='topics.Topic')),
            ],
        ),
    ]
