# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a2ausers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('01', 'USER comments on followed ANSWER'), ('02', 'USER answers followed QUESTION'), ('03', 'USER upvotes/downvotes ANSWER')], max_length=200)),
                ('parent_id', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_created', to='a2ausers.A2AUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='a2ausers.A2AUser')),
            ],
        ),
    ]
